app = "ski-jump-draft-staging"
primary_region = "waw"

[build]
dockerfile = "./Dockerfile"

[env]
ASPNETCORE_URLS = "http://0.0.0.0:8080"
ASPNETCORE_ENVIRONMENT = "Production"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0